import type { AssumptionDefinition } from '../types';

export const ASSUMPTIONS_CATALOG: AssumptionDefinition[] = [
  {
    id: 'A13',
    name: 'Network segmentation in operating environment',
    reference: 'QuBA-A13',
    stakeholder: 'Operator',
    description: 'The operating environment applies network segmentation that limits lateral movement from compromised product interfaces.',
    status: 'potentialAdditional',
    annexMappings: ['c', 'e'],
    effectType: 'scopeReduction',
    effectConfig: {
      targetDamageCategories: ['I', 'A'],
      sourceQuestionIds: ['QI14', 'QI15'],
      transformationNotes: ['Limit propagation to customer network segments.'],
      scopeImpactNotes: ['Reduces cross-network blast radius.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['network', 'segmentation'],
    allowedInMitigation: true,
  },
  {
    id: 'A14',
    name: 'Authenticated maintenance process',
    reference: 'QuBA-A14',
    stakeholder: 'Service',
    description: 'Maintenance operations are executed only by authenticated and authorized service personnel.',
    status: 'potentialAdditional',
    annexMappings: ['a', 'f'],
    effectType: 'attackStepConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA8', 'QA17'],
      transformationNotes: ['Reduces misuse of service interfaces.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['maintenance', 'authz'],
    allowedInMitigation: true,
  },
  {
    id: 'A15',
    name: 'Tamper evidence for enclosures',
    reference: 'QuBA-A15',
    stakeholder: 'Manufacturer',
    description: 'Physical opening of device enclosures leaves tamper evidence and is acted upon operationally.',
    status: 'potentialAdditional',
    annexMappings: ['j'],
    effectType: 'operationalConstraint',
    effectConfig: {
      targetDamageCategories: ['I', 'A'],
      transformationNotes: ['Deters covert physical manipulation.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['physical', 'tamper'],
    allowedInMitigation: true,
  },
  {
    id: 'A16',
    name: 'Hardened installation process',
    reference: 'QuBA-A16',
    stakeholder: 'Integrator',
    description: 'Installation and commissioning follow hardened procedures and verified checklists.',
    status: 'default',
    annexMappings: ['a', 'b'],
    effectType: 'operationalConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA14', 'QA15'],
      transformationNotes: ['Reduces deployment misconfiguration impact.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['deployment'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A17',
    name: 'Secure deployment environment',
    reference: 'QuBA-A17',
    stakeholder: 'Integrator',
    description: 'Deployment environment enforces baseline hardening controls.',
    status: 'default',
    annexMappings: ['a', 'c'],
    effectType: 'operationalConstraint',
    effectConfig: {
      targetDamageCategories: ['C', 'I', 'A'],
      transformationNotes: ['Assumes hardened baseline in installation environment.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['deployment', 'hardening'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A18',
    name: 'Secure production process',
    reference: 'QuBA-A18',
    stakeholder: 'Manufacturer',
    description: 'Secure production practices are applied and verified.',
    status: 'conditional',
    annexMappings: ['b', 'd'],
    effectType: 'attackStepConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA18'],
      transformationNotes: ['Constrains supply-chain and production compromise scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['production', 'supply-chain'],
    allowedInMitigation: true,
  },
  {
    id: 'A21',
    name: 'Customer-side attack scope limitation',
    reference: 'QuBA-A21',
    stakeholder: 'Customer',
    description: 'Attacks that require compromise of customer-managed systems are outside OEM product scope unless directly enabled by the product.',
    status: 'activeByTemplate',
    annexMappings: ['c', 'm'],
    effectType: 'scopeReduction',
    effectConfig: {
      targetDamageCategories: ['I', 'F'],
      sourceQuestionIds: ['QI15', 'QI16'],
      excludedScenarioKinds: ['customer-asset-access', 'customer-network-attack'],
      transformationNotes: ['Exclude customer-only attack consequences from baseline OEM risk rows.'],
      scopeImpactNotes: ['Keeps focus on OEM controllable attack outcomes.'],
      safetyException: true,
    },
    sourceSheet: 'Assumptions',
    tags: ['scope', 'customer'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A22',
    name: 'Credential management policy',
    reference: 'QuBA-A22',
    stakeholder: 'Operator',
    description: 'Strong credential rotation and lockout policy is enforced in operation.',
    status: 'potentialAdditional',
    annexMappings: ['f', 'g'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['C', 'I'],
      sourceQuestionIds: ['QI5', 'QI13'],
      transformationNotes: ['Reduces misuse impact of exposed credentials.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['credentials'],
    allowedInMitigation: true,
  },
  {
    id: 'A25',
    name: 'Protected debug interfaces in production',
    reference: 'QuBA-A25',
    stakeholder: 'Manufacturer',
    description: 'Debug and development interfaces are disabled or physically protected in production devices.',
    status: 'conditional',
    annexMappings: ['f', 'j'],
    effectType: 'attackStepConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA17'],
      transformationNotes: ['Constrains debug-interface attack surface.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['debug'],
    allowedInMitigation: true,
  },
  {
    id: 'A26',
    name: 'Secure service tooling',
    reference: 'QuBA-A26',
    stakeholder: 'Service',
    description: 'Service tooling used for diagnostics and updates is hardened and controlled.',
    status: 'potentialAdditional',
    annexMappings: ['g'],
    effectType: 'operationalConstraint',
    effectConfig: { transformationNotes: ['Reduces service-channel abuse probability.'] },
    sourceSheet: 'Assumptions',
    tags: ['service'],
    allowedInMitigation: true,
  },
  {
    id: 'A27',
    name: 'Restricted physical installation zones',
    reference: 'QuBA-A27',
    stakeholder: 'Operator',
    description: 'Product is installed in controlled areas with restricted physical access.',
    status: 'potentialAdditional',
    annexMappings: ['j'],
    effectType: 'scopeReduction',
    effectConfig: {
      targetDamageCategories: ['A', 'I'],
      sourceQuestionIds: ['QA14', 'QA16'],
      transformationNotes: ['Reduces public physical tampering scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['physical'],
    allowedInMitigation: true,
  },
  {
    id: 'A28',
    name: 'Monitored operational anomalies',
    reference: 'QuBA-A28',
    stakeholder: 'Operator',
    description: 'Operational anomalies are monitored and escalated with incident response workflows.',
    status: 'potentialAdditional',
    annexMappings: ['k'],
    effectType: 'outputOnly',
    effectConfig: {
      transformationNotes: ['Used for documentation and treatment rationale; no direct damage score change.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['monitoring'],
    allowedInMitigation: true,
  },
  {
    id: 'A29',
    name: 'Secure remote access governance',
    reference: 'QuBA-A29',
    stakeholder: 'Operator',
    description: 'Remote access to product management interfaces is governed through secure remote-access controls.',
    status: 'potentialAdditional',
    annexMappings: ['e', 'f'],
    effectType: 'attackStepConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA6', 'QA7', 'QA8'],
      transformationNotes: ['Constrains remote management abuse scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['remote-access'],
    allowedInMitigation: true,
  },
  {
    id: 'A30',
    name: 'Physical destruction out of scope',
    reference: 'QuBA-A30',
    stakeholder: 'Customer',
    description: 'Intentional physical destruction of the product is out of assessment scope for baseline cyber risk.',
    status: 'activeByTemplate',
    annexMappings: ['m'],
    effectType: 'scopeReduction',
    effectConfig: {
      targetDamageCategories: ['A'],
      excludedScenarioKinds: ['physical-destruction'],
      transformationNotes: ['Excludes destruction-only availability impacts from cyber baseline.'],
      scopeImpactNotes: ['Physical sabotage handled by separate safety/security assessment.'],
      safetyException: true,
    },
    sourceSheet: 'Assumptions',
    tags: ['scope', 'physical-destruction'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A31',
    name: 'Availability not safety relevant',
    reference: 'QuBA-A31',
    stakeholder: 'OEM',
    description: 'Loss of product availability is not safety-relevant in the intended operating context.',
    status: 'activeByTemplate',
    annexMappings: ['m'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['A'],
      sourceQuestionIds: ['QI6'],
      transformationNotes: ['Downgrades availability safety impact when only safety-based availability harm is claimed.'],
      safetyException: false,
    },
    sourceSheet: 'Assumptions',
    tags: ['availability', 'safety'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A34',
    name: 'Secure-by-default configuration',
    reference: 'QuBA-A34',
    stakeholder: 'Manufacturer',
    description: 'Product is shipped with secure-by-default settings and no insecure default credentials.',
    status: 'default',
    annexMappings: ['a', 'f'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['C', 'I'],
      sourceQuestionIds: ['QI5', 'QI13'],
      transformationNotes: ['Reduces severity of credential abuse baseline scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['defaults', 'credentials'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A36',
    name: 'Secure commissioning by trained personnel',
    reference: 'QuBA-A36',
    stakeholder: 'Integrator',
    description: 'Commissioning is carried out by trained personnel following verified procedures.',
    status: 'default',
    annexMappings: ['a'],
    effectType: 'operationalConstraint',
    effectConfig: { transformationNotes: ['Reduces configuration misuse during installation.'] },
    sourceSheet: 'Assumptions',
    tags: ['commissioning'],
    allowedInMitigation: true,
  },
  {
    id: 'A37',
    name: 'Protected logistics chain',
    reference: 'QuBA-A37',
    stakeholder: 'Manufacturer',
    description: 'Logistics and storage chain is protected against tampering and counterfeit insertion.',
    status: 'conditional',
    annexMappings: ['d'],
    effectType: 'attackStepConstraint',
    effectConfig: {
      sourceQuestionIds: ['QA19'],
      transformationNotes: ['Constrains supply-chain compromise scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['supply-chain'],
    allowedInMitigation: true,
  },
  {
    id: 'A38',
    name: 'Least privilege for provided credentials',
    reference: 'QuBA-A38',
    stakeholder: 'Manufacturer',
    description: 'Product-provided credentials follow least-privilege principles and are scoped to minimal required permissions.',
    status: 'activeByTemplate',
    annexMappings: ['f', 'h'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['C', 'I', 'F'],
      sourceQuestionIds: ['QI5', 'QI13'],
      transformationNotes: ['Reduces credential misuse impact by limiting reachable assets and actions.'],
      scopeImpactNotes: ['Does not remove safety exceptions.'],
      safetyException: true,
    },
    sourceSheet: 'Assumptions',
    tags: ['least-privilege', 'credentials'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A39',
    name: 'Authenticated telemetry channel',
    reference: 'QuBA-A39',
    stakeholder: 'Manufacturer',
    description: 'Telemetry channels are mutually authenticated and integrity-protected.',
    status: 'potentialAdditional',
    annexMappings: ['e'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['I'],
      transformationNotes: ['Reduces manipulation impact from forged telemetry.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['telemetry'],
    allowedInMitigation: true,
  },
  {
    id: 'A41',
    name: 'Documented vulnerability handling process',
    reference: 'QuBA-A41',
    stakeholder: 'Manufacturer',
    description: 'Manufacturer operates a vulnerability handling and coordinated disclosure process.',
    status: 'default',
    annexMappings: ['l'],
    effectType: 'outputOnly',
    effectConfig: {
      transformationNotes: ['Mainly affects reporting and governance outputs rather than baseline damage values.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['vulnerability-management'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A43',
    name: 'Sensing capabilities constrained by product design',
    reference: 'QuBA-A43',
    stakeholder: 'Manufacturer',
    description: 'Person-recognition and sensing capabilities are constrained by design and purpose limitation.',
    status: 'activeByTemplate',
    annexMappings: ['h', 'm'],
    effectType: 'damageTransformation',
    effectConfig: {
      targetDamageCategories: ['C'],
      sourceQuestionIds: ['QI1', 'QI2', 'QI11'],
      transformationNotes: ['Reduces privacy damage where sensing capability is technically restricted.'],
      scopeImpactNotes: ['Applies only if no safety exception is triggered.'],
      safetyException: true,
    },
    sourceSheet: 'Assumptions',
    tags: ['sensing', 'privacy'],
    activeByTemplate: true,
    allowedInMitigation: true,
  },
  {
    id: 'A44',
    name: 'Customer data retention policy enforced',
    reference: 'QuBA-A44',
    stakeholder: 'Customer',
    description: 'Customer enforces strict data retention and deletion controls in connected systems.',
    status: 'potentialAdditional',
    annexMappings: ['h'],
    effectType: 'scopeReduction',
    effectConfig: {
      targetDamageCategories: ['C', 'F'],
      sourceQuestionIds: ['QI2', 'QI11'],
      transformationNotes: ['Limits quantity and sensitivity of data exposed in breach scenarios.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['data-retention'],
    allowedInMitigation: true,
  },
  {
    id: 'A45',
    name: 'Legal review of contractual penalties',
    reference: 'QuBA-A45',
    stakeholder: 'OEM',
    description: 'Contractual cybersecurity obligations are periodically reviewed and updated by legal/compliance teams.',
    status: 'potentialAdditional',
    annexMappings: ['m'],
    effectType: 'outputOnly',
    effectConfig: {
      targetDamageCategories: ['F'],
      transformationNotes: ['Used for financial/legal penalty rationale in reports.'],
    },
    sourceSheet: 'Assumptions',
    tags: ['legal'],
    allowedInMitigation: true,
  },
];
