import { DamageLevelLabel } from '../enums';
import type { DamageRule } from '../types';

const rule = (seed: Omit<DamageRule, 'sourceSheet'>): DamageRule => ({
  ...seed,
  sourceSheet: 'Damage Scenarios',
});

export const DAMAGE_RULES: DamageRule[] = [
  rule({ id: 'DR-QI1-LOW', questionId: 'QI1', answerValue: 'low', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Person-recognition sensing exposure (low)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Sensing capability may expose limited identifying information.', note: 'Confidentiality privacy impact (low).', tags: ['privacy', 'sensing'] }),
  rule({ id: 'DR-QI1-SIGNIFICANT', questionId: 'QI1', answerValue: 'significant', category: 'C', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Person-recognition sensing exposure (significant)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Sensing capability can expose significant personal data.', note: 'High confidentiality/privacy impact.', tags: ['privacy', 'sensing'] }),
  rule({ id: 'DR-QI1-RUINOUS', questionId: 'QI1', answerValue: 'ruinous', category: 'C', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Person-recognition sensing exposure (ruinous)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Sensing capability can expose highly sensitive personal data at scale.', note: 'Critical privacy impact.', tags: ['privacy', 'sensing'] }),

  rule({ id: 'DR-QI2-LOW', questionId: 'QI2', answerValue: 'low', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Personal data disclosure (low)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Exposure of personal data with low sensitivity.', note: 'Personal data low impact.', tags: ['privacy'] }),
  rule({ id: 'DR-QI2-SIGNIFICANT', questionId: 'QI2', answerValue: 'significant', category: 'C', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Personal data disclosure (significant)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Exposure of significant personal data.', note: 'Personal data significant impact.', tags: ['privacy'] }),
  rule({ id: 'DR-QI2-RUINOUS', questionId: 'QI2', answerValue: 'ruinous', category: 'C', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Personal data disclosure (ruinous)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Exposure of large/sensitive personal data with severe legal and reputational effects.', note: 'Personal data ruinous impact.', tags: ['privacy'] }),

  rule({ id: 'DR-QI3-SLIGHT', questionId: 'QI3', answerValue: 'slightly-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'OEM IP exposure (slight innovation)', scenarioKind: 'ip-disclosure', damageNarrative: 'Loss of low-sensitivity OEM IP.', note: 'Low IP impact.', tags: ['ip'] }),
  rule({ id: 'DR-QI3-MODERATE', questionId: 'QI3', answerValue: 'moderately-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'OEM IP exposure (moderate innovation)', scenarioKind: 'ip-disclosure', damageNarrative: 'Loss of moderately innovative OEM IP.', note: 'Medium IP impact.', tags: ['ip'] }),
  rule({ id: 'DR-QI3-HIGH', questionId: 'QI3', answerValue: 'highly-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'OEM IP exposure (high innovation)', scenarioKind: 'ip-disclosure', damageNarrative: 'Loss of highly innovative IP and know-how.', note: 'High IP impact.', tags: ['ip'] }),

  rule({ id: 'DR-QI4-LOW', questionId: 'QI4', answerValue: 'low', category: 'F', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Breach of confidentiality obligations (low)', scenarioKind: 'legal-confidentiality', damageNarrative: 'Contractual/legal confidentiality obligations breached with limited impact.', note: 'Financial/legal low impact.', tags: ['legal'] }),
  rule({ id: 'DR-QI4-MEDIUM', questionId: 'QI4', answerValue: 'medium', category: 'F', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Breach of confidentiality obligations (medium)', scenarioKind: 'legal-confidentiality', damageNarrative: 'Confidentiality obligation breach with moderate penalties.', note: 'Financial/legal medium impact.', tags: ['legal'] }),
  rule({ id: 'DR-QI4-HIGH', questionId: 'QI4', answerValue: 'high', category: 'F', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Breach of confidentiality obligations (high)', scenarioKind: 'legal-confidentiality', damageNarrative: 'Significant contractual/legal secrecy breach penalties.', note: 'Financial/legal high impact.', tags: ['legal'] }),
  rule({ id: 'DR-QI4-CRITICAL', questionId: 'QI4', answerValue: 'critical', category: 'F', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Breach of confidentiality obligations (critical)', scenarioKind: 'legal-confidentiality', damageNarrative: 'Critical legal exposure due to secrecy breach.', note: 'Financial/legal critical impact.', tags: ['legal'] }),

  rule({ id: 'DR-QI5-LOW', questionId: 'QI5', answerValue: 'low', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Credential or crypto material misuse (low)', scenarioKind: 'credential-misuse', damageNarrative: 'Compromise of low-impact credentials/crypto material.', note: 'Credential misuse low confidentiality impact.', tags: ['credentials'] }),
  rule({ id: 'DR-QI5-MEDIUM', questionId: 'QI5', answerValue: 'medium', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Credential or crypto material misuse (medium)', scenarioKind: 'credential-misuse', damageNarrative: 'Compromise of credentials enabling unauthorized actions.', note: 'Credential misuse medium integrity impact.', tags: ['credentials'] }),
  rule({ id: 'DR-QI5-HIGH', questionId: 'QI5', answerValue: 'high', category: 'F', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Credential or crypto material misuse (high)', scenarioKind: 'credential-misuse', damageNarrative: 'Credential compromise affecting sensitive data and downstream systems.', note: 'Credential misuse high financial/legal impact.', tags: ['credentials'] }),
  rule({ id: 'DR-QI5-CRITICAL', questionId: 'QI5', answerValue: 'critical', category: 'F', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Credential or crypto material misuse (critical)', scenarioKind: 'credential-misuse', damageNarrative: 'Critical misuse of credential material across connected systems.', note: 'Credential misuse critical financial/legal impact.', tags: ['credentials'] }),

  rule({ id: 'DR-QI6-POTENTIAL', questionId: 'QI6', answerValue: 'potentially-dangerous', category: 'A', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Availability loss safety impact (potential danger)', scenarioKind: 'availability-safety', damageNarrative: 'Availability loss may create potentially dangerous situations.', note: 'Availability safety medium impact.', tags: ['availability', 'safety'] }),
  rule({ id: 'DR-QI6-LIGHT', questionId: 'QI6', answerValue: 'light-or-moderate-injury', category: 'A', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Availability loss safety impact (light/moderate injury)', scenarioKind: 'availability-safety', damageNarrative: 'Availability loss may lead to light or moderate injuries.', note: 'Availability safety high impact.', tags: ['availability', 'safety'] }),
  rule({ id: 'DR-QI6-SEVERE', questionId: 'QI6', answerValue: 'severe-injury', category: 'A', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Availability loss safety impact (severe injury)', scenarioKind: 'availability-safety', damageNarrative: 'Availability loss may lead to severe injuries.', note: 'Availability safety critical impact.', tags: ['availability', 'safety'] }),
  rule({ id: 'DR-QI6-LIFE', questionId: 'QI6', answerValue: 'life-threatening-injury', category: 'A', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Availability loss safety impact (life-threatening)', scenarioKind: 'availability-safety', damageNarrative: 'Availability loss may lead to life-threatening injuries.', note: 'Availability safety critical impact.', tags: ['availability', 'safety'] }),

  rule({ id: 'DR-QI7-DIST', questionId: 'QI7', answerValue: 'disturbance', category: 'A', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Operating environment disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Availability disturbance with manageable operational disruption.', note: 'Availability low impact.', tags: ['availability'] }),
  rule({ id: 'DR-QI7-SERVICE', questionId: 'QI7', answerValue: 'service-required', category: 'A', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Operating environment service required', scenarioKind: 'operational-disturbance', damageNarrative: 'Service intervention required due to reduced availability.', note: 'Availability medium impact.', tags: ['availability'] }),
  rule({ id: 'DR-QI7-MAJOR', questionId: 'QI7', answerValue: 'major-disturbance', category: 'A', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Operating environment major disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Major disturbance in operating environment due to loss of availability.', note: 'Availability high impact.', tags: ['availability'] }),
  rule({ id: 'DR-QI7-CRITICAL', questionId: 'QI7', answerValue: 'critical-disturbance', category: 'A', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Operating environment critical disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Critical disturbance in operating environment.', note: 'Availability critical impact.', tags: ['availability'] }),
  rule({ id: 'DR-QI7-ENV', questionId: 'QI7', answerValue: 'environmental-damage', category: 'A', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Environmental damage from availability impact', scenarioKind: 'environmental-damage', damageNarrative: 'Availability impact can cause environmental damage.', note: 'Availability high environmental impact.', tags: ['availability', 'environment'] }),
  rule({ id: 'DR-QI7-ENV-CRITICAL', questionId: 'QI7', answerValue: 'critical-environmental-damage', category: 'A', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Critical environmental damage from availability impact', scenarioKind: 'environmental-damage', damageNarrative: 'Availability impact can cause critical environmental damage.', note: 'Availability critical environmental impact.', tags: ['availability', 'environment'] }),

  rule({ id: 'DR-QI8-DIST', questionId: 'QI8', answerValue: 'disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Asset access due to availability loss (disturbance)', scenarioKind: 'customer-asset-access', damageNarrative: 'Loss of availability may indirectly enable limited asset access.', note: 'Integrity low impact.', tags: ['assets'] }),
  rule({ id: 'DR-QI8-SERVICE', questionId: 'QI8', answerValue: 'service-required', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Asset access due to availability loss (service required)', scenarioKind: 'customer-asset-access', damageNarrative: 'Availability loss requires service and raises asset access exposure.', note: 'Integrity medium impact.', tags: ['assets'] }),
  rule({ id: 'DR-QI8-MAJOR', questionId: 'QI8', answerValue: 'major-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Asset access due to availability loss (major disturbance)', scenarioKind: 'customer-asset-access', damageNarrative: 'Major disturbances can enable unauthorized access to customer assets.', note: 'Integrity high impact.', tags: ['assets'] }),
  rule({ id: 'DR-QI8-CRITICAL', questionId: 'QI8', answerValue: 'critical-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Asset access due to availability loss (critical disturbance)', scenarioKind: 'customer-asset-access', damageNarrative: 'Critical disturbances can enable critical unauthorized access.', note: 'Integrity critical impact.', tags: ['assets'] }),
  rule({ id: 'DR-QI8-PHYSICAL', questionId: 'QI8', answerValue: 'critical-disturbance', category: 'A', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Physical destruction consequence from bypass', scenarioKind: 'physical-destruction', damageNarrative: 'Availability loss can enable destructive physical actions on protected assets.', note: 'Physical destruction-related availability impact.', tags: ['physical', 'availability'] }),

  rule({ id: 'DR-QI9-LOW', questionId: 'QI9', answerValue: 'low', category: 'F', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Availability-related contractual penalties (low)', scenarioKind: 'contractual-penalty', damageNarrative: 'Minor contractual penalties due to availability issues.', note: 'Financial/legal low impact.', tags: ['contract'] }),
  rule({ id: 'DR-QI9-MEDIUM', questionId: 'QI9', answerValue: 'medium', category: 'F', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Availability-related contractual penalties (medium)', scenarioKind: 'contractual-penalty', damageNarrative: 'Moderate contractual penalties due to availability issues.', note: 'Financial/legal medium impact.', tags: ['contract'] }),
  rule({ id: 'DR-QI9-HIGH', questionId: 'QI9', answerValue: 'high', category: 'F', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Availability-related contractual penalties (high)', scenarioKind: 'contractual-penalty', damageNarrative: 'High contractual penalties due to availability issues.', note: 'Financial/legal high impact.', tags: ['contract'] }),
  rule({ id: 'DR-QI9-CRITICAL', questionId: 'QI9', answerValue: 'critical', category: 'F', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Availability-related contractual penalties (critical)', scenarioKind: 'contractual-penalty', damageNarrative: 'Critical contractual/legal penalties due to sustained outages.', note: 'Financial/legal critical impact.', tags: ['contract'] }),

  rule({ id: 'DR-QI10-POTENTIAL', questionId: 'QI10', answerValue: 'potentially-dangerous', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Manipulation safety impact (potential danger)', scenarioKind: 'manipulation-safety', damageNarrative: 'Manipulated behavior can create potentially dangerous situations.', note: 'Integrity medium safety impact.', tags: ['integrity', 'safety'] }),
  rule({ id: 'DR-QI10-LIGHT', questionId: 'QI10', answerValue: 'light-or-moderate-injury', category: 'I', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulation safety impact (light/moderate injury)', scenarioKind: 'manipulation-safety', damageNarrative: 'Manipulation can lead to light or moderate injuries.', note: 'Integrity high safety impact.', tags: ['integrity', 'safety'] }),
  rule({ id: 'DR-QI10-SEVERE', questionId: 'QI10', answerValue: 'severe-injury', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulation safety impact (severe injury)', scenarioKind: 'manipulation-safety', damageNarrative: 'Manipulation can lead to severe injuries.', note: 'Integrity critical safety impact.', tags: ['integrity', 'safety'] }),
  rule({ id: 'DR-QI10-LIFE', questionId: 'QI10', answerValue: 'life-threatening-injury', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulation safety impact (life-threatening)', scenarioKind: 'manipulation-safety', damageNarrative: 'Manipulation can lead to life-threatening injuries.', note: 'Integrity critical safety impact.', tags: ['integrity', 'safety'] }),

  rule({ id: 'DR-QI11-LOW', questionId: 'QI11', answerValue: 'low', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Manipulated product personal data disclosure (low)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Manipulated product may expose low-sensitivity personal data.', note: 'Confidentiality low impact.', tags: ['privacy', 'manipulation'] }),
  rule({ id: 'DR-QI11-SIGNIFICANT', questionId: 'QI11', answerValue: 'significant', category: 'C', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated product personal data disclosure (significant)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Manipulation exposes significant personal data.', note: 'Confidentiality high impact.', tags: ['privacy', 'manipulation'] }),
  rule({ id: 'DR-QI11-RUINOUS', questionId: 'QI11', answerValue: 'ruinous', category: 'C', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulated product personal data disclosure (ruinous)', scenarioKind: 'personal-data-exposure', damageNarrative: 'Manipulation causes ruinous personal data exposure.', note: 'Confidentiality critical impact.', tags: ['privacy', 'manipulation'] }),

  rule({ id: 'DR-QI12-SLIGHT', questionId: 'QI12', answerValue: 'slightly-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Manipulated product IP disclosure (slight)', scenarioKind: 'ip-disclosure', damageNarrative: 'Manipulated product may disclose low-value IP.', note: 'Confidentiality low impact.', tags: ['ip', 'manipulation'] }),
  rule({ id: 'DR-QI12-MODERATE', questionId: 'QI12', answerValue: 'moderately-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Manipulated product IP disclosure (moderate)', scenarioKind: 'ip-disclosure', damageNarrative: 'Manipulated product may disclose moderately innovative IP.', note: 'Confidentiality medium impact.', tags: ['ip', 'manipulation'] }),
  rule({ id: 'DR-QI12-HIGH', questionId: 'QI12', answerValue: 'highly-innovative', category: 'C', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated product IP disclosure (high)', scenarioKind: 'ip-disclosure', damageNarrative: 'Manipulated product may disclose highly innovative IP.', note: 'Confidentiality high impact.', tags: ['ip', 'manipulation'] }),

  rule({ id: 'DR-QI13-LOW', questionId: 'QI13', answerValue: 'low', category: 'I', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Manipulated credential misuse (low)', scenarioKind: 'credential-misuse', damageNarrative: 'Manipulated product may misuse low-impact credentials.', note: 'Integrity low impact.', tags: ['credentials', 'manipulation'] }),
  rule({ id: 'DR-QI13-MEDIUM', questionId: 'QI13', answerValue: 'medium', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Manipulated credential misuse (medium)', scenarioKind: 'credential-misuse', damageNarrative: 'Manipulated product may misuse credentials to alter connected systems.', note: 'Integrity medium impact.', tags: ['credentials', 'manipulation'] }),
  rule({ id: 'DR-QI13-HIGH', questionId: 'QI13', answerValue: 'high', category: 'F', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated credential misuse (high)', scenarioKind: 'credential-misuse', damageNarrative: 'Credential/crypto misuse can cause major financial and legal damages.', note: 'Financial/legal high impact.', tags: ['credentials', 'manipulation'] }),
  rule({ id: 'DR-QI13-CRITICAL', questionId: 'QI13', answerValue: 'critical', category: 'F', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulated credential misuse (critical)', scenarioKind: 'credential-misuse', damageNarrative: 'Credential/crypto misuse can cause critical financial and legal damages.', note: 'Financial/legal critical impact.', tags: ['credentials', 'manipulation'] }),

  rule({ id: 'DR-QI14-DIST', questionId: 'QI14', answerValue: 'disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Manipulated operational disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Manipulation causes limited disturbance in operating environment.', note: 'Integrity low impact.', tags: ['integrity', 'operations'] }),
  rule({ id: 'DR-QI14-SERVICE', questionId: 'QI14', answerValue: 'service-required', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Manipulated operational service required', scenarioKind: 'operational-disturbance', damageNarrative: 'Manipulation requires service intervention.', note: 'Integrity medium impact.', tags: ['integrity', 'operations'] }),
  rule({ id: 'DR-QI14-MAJOR', questionId: 'QI14', answerValue: 'major-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated major operational disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Manipulation causes major operational disturbance.', note: 'Integrity high impact.', tags: ['integrity', 'operations'] }),
  rule({ id: 'DR-QI14-CRITICAL', questionId: 'QI14', answerValue: 'critical-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulated critical operational disturbance', scenarioKind: 'operational-disturbance', damageNarrative: 'Manipulation causes critical operational disturbance.', note: 'Integrity critical impact.', tags: ['integrity', 'operations'] }),
  rule({ id: 'DR-QI14-ENV', questionId: 'QI14', answerValue: 'environmental-damage', category: 'I', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated environmental damage', scenarioKind: 'environmental-damage', damageNarrative: 'Manipulation can trigger environmental damage.', note: 'Integrity high environmental impact.', tags: ['integrity', 'environment'] }),
  rule({ id: 'DR-QI14-ENV-CRITICAL', questionId: 'QI14', answerValue: 'critical-environmental-damage', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulated critical environmental damage', scenarioKind: 'environmental-damage', damageNarrative: 'Manipulation can trigger critical environmental damage.', note: 'Integrity critical environmental impact.', tags: ['integrity', 'environment'] }),

  rule({ id: 'DR-QI15-DIST', questionId: 'QI15', answerValue: 'disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Customer asset/network access (disturbance)', scenarioKind: 'customer-network-attack', damageNarrative: 'Manipulation may enable low-impact asset/network access.', note: 'Integrity low impact.', tags: ['assets', 'network'] }),
  rule({ id: 'DR-QI15-SERVICE', questionId: 'QI15', answerValue: 'service-required', category: 'I', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Customer asset/network access (service required)', scenarioKind: 'customer-network-attack', damageNarrative: 'Manipulation may enable moderate customer-network attacks.', note: 'Integrity medium impact.', tags: ['assets', 'network'] }),
  rule({ id: 'DR-QI15-MAJOR', questionId: 'QI15', answerValue: 'major-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Customer asset/network access (major disturbance)', scenarioKind: 'customer-network-attack', damageNarrative: 'Manipulation may enable major customer-network compromise.', note: 'Integrity high impact.', tags: ['assets', 'network'] }),
  rule({ id: 'DR-QI15-CRITICAL', questionId: 'QI15', answerValue: 'critical-disturbance', category: 'I', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Customer asset/network access (critical disturbance)', scenarioKind: 'customer-network-attack', damageNarrative: 'Manipulation may enable critical customer-network compromise.', note: 'Integrity critical impact.', tags: ['assets', 'network'] }),

  rule({ id: 'DR-QI16-LOW', questionId: 'QI16', answerValue: 'low', category: 'F', damageLevelLabel: DamageLevelLabel.Low, damageLevelValue: 2, scenarioLabel: 'Manipulated product contractual penalties (low)', scenarioKind: 'contractual-penalty', damageNarrative: 'Manipulated behavior may trigger low contractual penalties.', note: 'Financial/legal low impact.', tags: ['contract', 'legal'] }),
  rule({ id: 'DR-QI16-MEDIUM', questionId: 'QI16', answerValue: 'medium', category: 'F', damageLevelLabel: DamageLevelLabel.Medium, damageLevelValue: 3, scenarioLabel: 'Manipulated product contractual penalties (medium)', scenarioKind: 'contractual-penalty', damageNarrative: 'Manipulated behavior may trigger medium contractual penalties.', note: 'Financial/legal medium impact.', tags: ['contract', 'legal'] }),
  rule({ id: 'DR-QI16-HIGH', questionId: 'QI16', answerValue: 'high', category: 'F', damageLevelLabel: DamageLevelLabel.High, damageLevelValue: 4, scenarioLabel: 'Manipulated product contractual penalties (high)', scenarioKind: 'contractual-penalty', damageNarrative: 'Manipulated behavior may trigger high contractual/legal penalties.', note: 'Financial/legal high impact.', tags: ['contract', 'legal'] }),
  rule({ id: 'DR-QI16-CRITICAL', questionId: 'QI16', answerValue: 'critical', category: 'F', damageLevelLabel: DamageLevelLabel.Critical, damageLevelValue: 5, scenarioLabel: 'Manipulated product contractual penalties (critical)', scenarioKind: 'contractual-penalty', damageNarrative: 'Manipulated behavior may trigger critical legal penalties.', note: 'Financial/legal critical impact.', tags: ['contract', 'legal'] }),
];
