import { NavGroup, SheetStatus } from '../enums';
import type { SheetDefinition } from '../types';

export const SHEET_METADATA: SheetDefinition[] = [
  {
    id: 'license',
    sheetName: 'License',
    route: '/license',
    navGroup: NavGroup.Meta,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Informazioni sulla licenza del template QuBA.',
    dependsOn: [],
    expectedData: ['Testo licenza', 'Riferimenti d’uso'],
  },
  {
    id: 'readme',
    sheetName: 'README',
    route: '/readme',
    navGroup: NavGroup.Meta,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Guida rapida all’uso della webapp e del flusso QuBA.',
    dependsOn: [],
    expectedData: ['Istruzioni operative', 'Link alle sezioni principali'],
  },
  {
    id: 'version-history',
    sheetName: 'Version History',
    route: '/version-history',
    navGroup: NavGroup.Meta,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Storico versioni template e release notes.',
    dependsOn: [],
    expectedData: ['Versione', 'Data', 'Autore', 'Note rilascio'],
  },
  {
    id: 'definitions',
    sheetName: 'Definitions',
    route: '/definitions',
    navGroup: NavGroup.Cataloghi,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Cataloghi e scale normative (DL/RAP/Risk matrix).',
    dependsOn: ['questions'],
    expectedData: ['Damage levels', 'RAP thresholds', 'Risk matrix'],
  },
  {
    id: 'questions',
    sheetName: 'Questions',
    route: '/questions',
    navGroup: NavGroup.Cataloghi,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Catalogo master domande QI/QA.',
    dependsOn: [],
    expectedData: ['Question IDs', 'Testi', 'Regole answer2/rationale'],
  },
  {
    id: 'damage-scenarios',
    sheetName: 'Damage Scenarios',
    route: '/damage-scenarios',
    navGroup: NavGroup.Analisi,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Scenari di danno derivati dal questionario.',
    dependsOn: ['questionnaire', 'definitions'],
    expectedData: ['DS IDs', 'Categoria C/I/A/F', 'DL'],
  },
  {
    id: 'attack-steps',
    sheetName: 'Attack Steps',
    route: '/attack-steps',
    navGroup: NavGroup.Analisi,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Catalogo/istanza Attack Steps e stato attivazione.',
    dependsOn: ['questionnaire'],
    expectedData: ['AS IDs', 'Active flag', 'Base EASE', 'RAP'],
  },
  {
    id: 'assumptions',
    sheetName: 'Assumptions',
    route: '/assumptions',
    navGroup: NavGroup.Cataloghi,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Catalogo assunzioni e impatti.',
    dependsOn: [],
    expectedData: ['A IDs', 'Stakeholder', 'Effects'],
  },
  {
    id: 'countermeasures',
    sheetName: 'Countermeasures',
    route: '/countermeasures',
    navGroup: NavGroup.Cataloghi,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Catalogo contromisure e delta EASE.',
    dependsOn: [],
    expectedData: ['C/CM IDs', 'Type', 'Ease delta', 'Annex mapping'],
  },
  {
    id: 'documentation',
    sheetName: 'Documentation',
    route: '/documentation',
    navGroup: NavGroup.Input,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Metadati analisi e contatti.',
    dependsOn: [],
    expectedData: ['TOE name', 'Author', 'Contacts', 'Version'],
  },
  {
    id: 'questionnaire',
    sheetName: 'Questionnaire',
    route: '/questionnaire',
    navGroup: NavGroup.Input,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Raccolta risposte QI/QA.',
    dependsOn: ['questions'],
    expectedData: ['Answer1', 'Answer2', 'Rationale'],
  },
  {
    id: 'ds-overview',
    sheetName: 'DS Overview',
    route: '/ds-overview',
    navGroup: NavGroup.Analisi,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Sintesi damage scenarios attivi.',
    dependsOn: ['damage-scenarios'],
    expectedData: ['DS attivi', 'DL', 'Commenti'],
  },
  {
    id: 'risks',
    sheetName: 'Risks',
    route: '/risks',
    navGroup: NavGroup.Analisi,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Risk register calcolato.',
    dependsOn: ['attack-steps', 'damage-scenarios'],
    expectedData: ['Risk ID', 'RAP', 'DL', 'Risk level'],
  },
  {
    id: 'mitigation',
    sheetName: 'Mitigation',
    route: '/mitigation',
    navGroup: NavGroup.Trattamento,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Pianificazione mitigazioni C&A.',
    dependsOn: ['risks', 'countermeasures', 'assumptions'],
    expectedData: ['Input C&A IDs', 'N-RAP', 'N-Risk'],
  },
  {
    id: 'risk-treatment',
    sheetName: 'Risk Treatment',
    route: '/risk-treatment',
    navGroup: NavGroup.Trattamento,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Decisioni trattamento rischio.',
    dependsOn: ['risks'],
    expectedData: ['Decision', 'Rationale', 'Comment'],
  },
  {
    id: 'result-summary',
    sheetName: 'Result Summary',
    route: '/result-summary',
    navGroup: NavGroup.Output,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Riepilogo finale item attivi.',
    dependsOn: ['mitigation'],
    expectedData: ['A/C attive', 'Stakeholder', 'Reference'],
  },
  {
    id: 'annex-i-1-2-report',
    sheetName: 'Annex I 1.2 Report',
    route: '/annex-i-1-2-report',
    navGroup: NavGroup.Output,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Mappatura requisiti CRA Annex I 1.2.',
    dependsOn: ['result-summary'],
    expectedData: ['Requirement letter', 'Status', 'Implemented by'],
  },
  {
    id: 'tracing',
    sheetName: 'Tracing',
    route: '/tracing',
    navGroup: NavGroup.Trattamento,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Conferma implementazione mitigazioni.',
    dependsOn: ['mitigation', 'risk-treatment'],
    expectedData: ['Planned', 'Confirmed', 'T-Risk'],
  },
  {
    id: 'tasks',
    sheetName: 'Tasks',
    route: '/tasks',
    navGroup: NavGroup.Controlli,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'TODO e anomalie operative.',
    dependsOn: ['quality-indicators'],
    expectedData: ['Task ID', 'Origine', 'Commento'],
  },
  {
    id: 'quality-indicators',
    sheetName: 'Quality Indicators',
    route: '/quality-indicators',
    navGroup: NavGroup.Controlli,
    advanced: false,
    status: SheetStatus.Implemented,
    description: 'Cruscotto qualità completezza/coerenza.',
    dependsOn: ['documentation', 'questionnaire'],
    expectedData: ['Indicator ID', 'Severity', 'Count', 'Details'],
  },
  {
    id: 'json-export',
    sheetName: 'JSON',
    route: '/json-export',
    navGroup: NavGroup.Output,
    advanced: false,
    status: SheetStatus.Placeholder,
    description: 'Esportazione JSON strutturata.',
    dependsOn: ['result-summary', 'risk-treatment'],
    expectedData: ['Payload JSON', 'Copy action'],
  },
  {
    id: 'user-information',
    sheetName: 'User Information',
    route: '/user-information',
    navGroup: NavGroup.Advanced,
    advanced: true,
    status: SheetStatus.Placeholder,
    description: 'Informazioni utente CRA (advanced).',
    dependsOn: ['documentation'],
    expectedData: ['Manufacturer info', 'Support period', 'Safe use notes'],
  },
  {
    id: 'profile-definitions',
    sheetName: 'Profile Definitions',
    route: '/profile-definitions',
    navGroup: NavGroup.Advanced,
    advanced: true,
    status: SheetStatus.Placeholder,
    description: 'Fixture profili/regressione (advanced).',
    dependsOn: ['questionnaire'],
    expectedData: ['Sample profile', 'Apply/import actions'],
  },
  {
    id: 'helper',
    sheetName: 'Helper',
    route: '/helper',
    navGroup: NavGroup.Advanced,
    advanced: true,
    status: SheetStatus.Placeholder,
    description: 'Diagnostica interna e contatori (advanced).',
    dependsOn: ['all'],
    expectedData: ['Counts', 'Debug info', 'Parity traces'],
  },
];

export const SHEET_METADATA_BY_ROUTE = Object.fromEntries(
  SHEET_METADATA.map((sheet) => [sheet.route, sheet]),
) as Record<string, SheetDefinition>;

export const getVisibleSheets = (advancedMode: boolean): SheetDefinition[] =>
  SHEET_METADATA.filter((sheet) => !sheet.advanced || advancedMode);
